name: Backport

on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport closed pull request
    steps:
    - uses: syndesisio/backport-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
