name: Backport

on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport closed pull request
    steps:
    - run: cat "${GITHUB_EVENT_PATH}"
    - uses: syndesisio/backport-action@master
